spring.application.name=tfg-estimacion-esfuerzo

spring.config.import=optional:file:./application-local.properties

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/tfg_estimacion_esfuerzo}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.thymeleaf.check-template-location=false